# Generated by Django 5.2.7 on 2025-10-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_unit_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='shor_name',
            new_name='short_name',
        ),
    ]
