# Generated by Django 5.2.7 on 2025-10-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_shor_name_unit_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
