# Generated by Django 5.2.7 on 2025-10-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_ingredient_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='kcal_per_100g',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
