# Generated by Django 5.2.7 on 2025-10-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_prep_time_recipe_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
